### ISSUE TITLE
Wrong detection of the road in road_drone_textures.world

### ISSUE THREAD

**Issue by reysam93** [JdeRobot/JdeRobot#404]
The camera of the drone do not see the road in road_drone_textures.world. I think it is due to the mud_box block, because I have changed them for the grass_plane models and it works.
I put an image of what the camera sees.
![followroadbug](https://cloud.githubusercontent.com/assets/10724295/14243558/9f2e1bc0-fa56-11e5-8f07-fd4865452813.png)

**Comment by aitormf** [comment]
I close this issue because now works well:

Python:
![captura de pantalla de 2017-05-12 11-01-12](https://cloud.githubusercontent.com/assets/16046048/25991102/74b44db2-3702-11e7-8e50-dd98f0ae8db8.png)

C++:
![captura de pantalla de 2017-05-12 10-57-27](https://cloud.githubusercontent.com/assets/16046048/25991135/8bf6dd8c-3702-11e7-8129-51d5710b549c.png)
