### ISSUE TITLE
 portability: test of 'Simulated ArDrone + introrob.py' from Windows

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/JdeRobot#420]
Similar to #419 but with a Pyhton component instead of a C++ one. 

One attractive feature is portability, to use JdeRobot from other Operating Systems. Docker may help on this. Let's do a test running part of the 'Simulated ArDrone + introrob.py' example in TeachingRobotics [http://jderobot.org/Teaching_robotics_with_JdeRobot#Simulated_ArDrone_.2B_introrob_py] on a Windows machine. Gazebo will run on a Linux machine as usual, but the introrob.py component should run on a Windows machine.

**Comment by aitormf** [comment]
It is not exactly the same, but I could use the exercise Teaching Robotics of FollowLines on Windows, running gazebo in a [Docker ](http://www.docker.com/)(comes to be similar to a virtual machine).
You can use the same dependencies versions that in Ubuntu (Python 2.7, PyQt4, Qt4.8.7,...) excepts **OpenCV** and **Ice**.

- OpenCV: I saw the 3.1 versión to Python and when I tried it, Works without any code change.
- Ice: I use 3.6 versión because I could not run 3.5.  It works without any code change.

![c4e6a910-5823-11e6-899a-f57675508b53](https://cloud.githubusercontent.com/assets/16046048/17321423/cfc7cb96-5898-11e6-9f03-bb531e37cb20.png)

I decided start by this instead of Introboy_py because firstly I had problems with a dependencie of introrob_py (PyQwt to flying Indicators) and because FollowLines only has 2 Ice Interfaces (camera and motors).

I needed change EasyIceConfig library because it has harcoded paths that no Works in Windows. And now I'm doing Parallelice_py library because the architecture of TeachingRobotic clients does that their GUI to hang while the sensor data are being received from the server.

![image](https://cloud.githubusercontent.com/assets/16046048/17321861/f0cb85ce-589a-11e6-825c-21ee4e82275b.png)


**Instructions to install all depedencies in Windows:**

1. Download python 2.7.12 and install checked env variables (Is posible that you need restart to run the PATH): [https://www.python.org/ftp/python/2.7.12/python-2.7.12.amd64.msi](https://www.python.org/ftp/python/2.7.12/python-2.7.12.amd64.msi)

2. Download qt 4.8.7: [http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-vs2010-4.8.7.exe
](http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-vs2010-4.8.7.exe)

3. update pip:
<pre>python -m pip install --upgrade pip</pre>

4. Install deps:
<pre>pip install numpy zeroc-ice
pip install http://jderobot.org/store/aitormf/uploads/windows/opencv_python-3.1.0-cp27-cp27m-win_amd64.whl
pip install http://jderobot.org/store/aitormf/uploads/windows/PyQt4-4.11.4-cp27-none-win_amd64.whl
pip install http://jderobot.org/store/aitormf/uploads/windows/PyQwt-5.2.1-cp27-none-win_amd64.whl
</pre>

5. Install jderobot libraries and unzip in c:\python27\Lib:  [http://jderobot.org/store/aitormf/uploads/windows/jderobot_cp27_win64.zip](http://jderobot.org/store/aitormf/uploads/windows/jderobot_cp27_win64.zip)

6. Download TeachingRobotics and run from CMD

**Comment by aitormf** [comment]
Now we can use introrob py + simulated Ardrone in Windows (video):
[![Introrob py in Windows ](http://img.youtube.com/vi/Pz-2lVtZCqQ/0.jpg)](http://www.youtube.com/watch?v=Pz-2lVtZCqQ)

**Comment by aitormf** [comment]
this issue is resolved with #543
