### ISSUE TITLE
custom command inside visualHFSM makes compilation fail

### ISSUE THREAD

**Issue by chanfr** [JdeRobot/JdeRobot#475]
Hi all,

the following line inside visualHFSM cmake component:

add_custom_command(TARGET visualHFSM_interfaces POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_SOURCE_DIR}/allinterfaces.txt $<TARGET_FILE_DIR:visualHFSM>)

is not working and makes the compilation fail at least while compiling with multiple threads

**Comment by reysam93** [comment]
Hello,
I do not know much about CMake, so I am not sure of what this command do, but the file allinterfaces.txt is not important for VisualHFSM, is just a temporal file for reading the interfaces, this is why I deleted it from the repository. 
I guess it will be failing because CMake does not find the file, but if this command only copy this file I think it is not necessary for the installation  of VisualHFSM.
Does the command do something else apart from copying allinterfaces.txt ?
