### ISSUE TITLE
ardrone_server won't move the drone

### ISSUE THREAD

**Issue by mazafrav** [JdeRobot/JdeRobot#833]
I'm having some problems with **ardrone_server**, while it succesfully sends some commands like takeoff and land to the drone, the commands sent through **CMDvel** won't make the drone move.
I have tried moving it with my own component and with uav_viewer but neither of them worked. Furthermore, it works completely fine in simulation.

**Comment by aitormf** [comment]
Hi @mazafrav, I have been trying _ardrone_server_ with **uav_viewer** and **uav_viewer_py**.

This is a problem in the tools  (C++ and your) because with  **uav_viewer_py** it works well. Try to limit the maximum velocity to be send. In uav_viewer_py the limits are:

MAX_LINX = 0.1
MAX_LINY = 0.3
MAX_LINZ = 0.3
MAX_ANGZ = 0.4
