### ISSUE TITLE
[Tools] cameraview_py displays output in BGR color space

### ISSUE THREAD

**Issue by ni9elf** [JdeRobot/JdeRobot#888]
The color space used by camerview_py is BGR instead of RGB. The following line in OpenCV will convert the color space to RGB and solve the issue:
`image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)`

**Comment by aitormf** [comment]
Hi @ni9elf, 
The problem is backwards, Imshow uses images in BGR and we give it in RGB, so it looks bad, we have to move from RGB to BGR instead of BGR to RGB (in practice, for this case, is the same because both swap channels R and B)
[source](https://stackoverflow.com/questions/38598118/difference-between-plt-show-and-cv2-imshow)

**Comment by ni9elf** [comment]
Hi @aitormf 
Thanks for the feedback. Yes, RGB to BGR will be technically correct.

**Comment by aitormf** [comment]
solved with #889
